### ISSUE TITLE
The "analytics.yahoo.com tracker" is wrongly blocked on L1 lists

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FastBlockShield#131] opened 2018-09-14 11:40 UTC
**[Affected versions]:**
  -  Beta 63.0b5

**[Affected Platforms]:**
 - Windows 10 x64
- Windows 7 x64

**[Prerequisites]:**
- Have the following prefs:
	- shieldStudy.logLevel to All
 	- extensions.fastblock_shield_mozilla_org.test.variationName to FB2L1
	- Extensions.legacy.enabled;true
	- Xpinstall.signatures.required;false
- The Fastblock signed add-on is installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open the browser console (CTRL+SHIFT+J)
3. Navigate to nytimes.com
4. Observe the blocked trackers in the browser console.

**[Expected result]:**
- No tracker from the following list should be displayed as blocked: https://bugzilla.mozilla.org/attachment.cgi?id=9007050

**[Actual results]:**
- The "analytics.yahoo.com" tracker is displayed as blocked in the browser console.

**[Notes]:**
- Attached a screen recording of the issue:
https://drive.google.com/open?id=1yrWTXruU9GVszAsdbjYUF63JD3Pyselg

**Comment by englehardt** [comment] 2018-09-14 12:16
The video shows that a resource from `analytics.yahoo.com` was blocked because it is served with the header `X-Content-Type-Options: no-sniff`. The resource does not appear to have been blocked by FastBlock.

**Comment by johannhof** [comment] 2018-09-14 12:19
Yeah, I can confirm that this is harmless. Closing!

**Closed by johannhof** 2018-09-14 12:19 UTC
