### ISSUE TITLE
Multiple Windows Not Firing

### ISSUE THREAD

**Issue by ericawright** [mozilla/FastBlockShield#50] opened 2018-08-16 18:22 UTC
- open `https://bugzilla.mozilla.org/` in a new window
- refresh more than 6 times

AR:

- never see a popup nor pings in the console

ER: 
- see a popup and console pings

**Comment by johannhof** [comment] 2018-08-16 19:17
Isn't this a dupe of #41? :)

**Closed as completed** 2018-08-16 19:19 UTC
